title: Hello, world! I'm Annabell Rodriguez
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Annabell Rodríguez, a Machine Learning analyst with a passion for problem-solving and software development. 
  As a student pursuing a diploma certificate in Machine Learning, I'm constantly seeking out opportunities to expand my knowledge and skills in this exciting field. 
  My background in software development, particularly my experience with .NET, has given me a strong foundation in object-oriented programming principles and a deep understanding of how to develop high-quality applications. 
  I'm proficient in languages such as C# and python, and I'm always looking for ways to improve my coding skills.
  What I love most about Machine Learning is the opportunity to apply advanced mathematical concepts to real-world problems. 
  I find it incredibly rewarding to tackle complex challenges and find innovative solutions that can make a real difference in people's lives.
  I'm committed to staying up-to-date with the latest developments in machine learning, and I'm always on the lookout for new tools and techniques to improve my skills. 
  I'm a creative problem-solver who isn't afraid to think outside the box to find solutions to difficult problems.
  If you're interested in following my journey as a Machine Learning developer and Software Developer, be sure to check out my GitHub page. 
  You'll find some exciting projects there that demonstrate my skills and expertise in this field.
permalink: ':title/'
baseurl: "/arodriguezva/arodriguezva.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Annabell Rodriguez # add your name
author-img: 20230228_0037290.jpg # add your photo
about-author: I'm a Machine Learning analyst constantly seeking out opportunities to expand my knowledge and skills in this exciting field. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: arodriguezva # add your Github handle
social-linkedin: https://www.linkedin.com/in/annabellrv/?locale=en_US # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
